version: '2.1'
volumes:
  travel_data:
    external: true

services:
  app:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    links:
      - database
    volumes:
      - /usr/app/node_modules
      - ../../:/usr/app
    ports:
      - "5000:5000"
    environment:
      DATABASE_USERNAME: "travel"
      DATABASE_PASSWORD: "travel"
      DATABASE_NAME: "travel"
      DATABASE_HOST: "database"
      DATABASE_DIALECT: "postgres"
      DATABASE_PORT: "5432"
    entrypoint:
      - /usr/app/docker/dev/docker-entrypoint.sh
    command:
      - yarn
      - start:dev
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres
    expose:
      - '5432'
    volumes:
      - travel_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: travel
      POSTGRES_PASSWORD: travel
      POSTGRES_DB: travel
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
