version: '2.1'
volumes:
  travella_data:
    external: true

services:
  app:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    links:
      - database
    volumes:
      - /usr/app/node_modules
      - ../../:/usr/app
    ports:
      - '5000:5000'
    environment:
      PORT: 5000
      DATABASE_URL: postgres://travella:travella@database/travella
    entrypoint:
      - /usr/app/docker/dev/entrypoint.sh
    command:
      - yarn
      - start:dev
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres
    expose:
      - '5432'
    ports:
      - '5433:5432'
    volumes:
      - travella_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: travella
      POSTGRES_PASSWORD: travella
      POSTGRES_DB: travella
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 5
